endpoints:
  restart:
    enabled: true

spring:
  application:
    name: <%= baseName %>
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApgFGw4vtRMGp5mR6T4PSrt6IR4wrRi//uHrNQHnz0jwL9kQRVdhj80uAbDn2fR9Y+2A20LAmGZnO8N7iYlOo4+XQGKus9ZW826YULeSC7/PML01bLvDcuCaowy80+xawxWB2KaiDFa6PtCnh5+kDrkp4lsBN8YA1XoVpSDleECpzOZdWhcp7TEIEpZmYJB6YaT5cuZ1DRhV7zOcB/7MZNAK45wmUEr0NZvVXLNuYQ6NvSKfUBIpIZHS4yPcbC4KI2CNU2M7LyUppbuNKlLiHEBWcjuJY1D1TsteMAJzyjSeSc7+rKd3PQsX63bP0dP6on/YzIi+WOUpWpNlg6Qq5/QIDAQAB
          -----END PUBLIC KEY-----

server:
  port: <%= serverPort %>
  contextPath: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: <%= eurekaUri %>
#http://localhost:8002/eureka/
  instance:
     preferIpAddress: true
